export const chapters=[
 {id:'threshold',name:'Ngưỡng cửa',en:'Continuum',title:['Bước qua','điều quen thuộc.'],text:'Một hành trình qua tám hình thái. Để ánh sáng dẫn lối và trí tưởng tượng đi xa hơn.',label:'TRIỂN LÃM CỦA NHỮNG ĐIỀU CHƯA TỒN TẠI',note:'Mọi kết thúc đều có thể là một khởi đầu.',side:'left'},
 {id:'unfold',name:'Khai mở',en:'Aperture',title:['Mở ra.','Không giới hạn.'],text:'Vòng lặp dần tháo khỏi chính mình. Một đường xoắn mở ra chiều sâu nơi từng chỉ có bề mặt.',label:'HÌNH HÀI CỦA KHẢ NĂNG',note:'Đôi khi, thay đổi bắt đầu từ một khe hở.',side:'right'},
 {id:'orbit',name:'Quỹ đạo',en:'Orbit',title:['Xa nhau.','Vẫn kết nối.'],text:'Những đường đi riêng cùng tìm thấy một tâm điểm. Khoảng trống cũng là một phần của tác phẩm.',label:'NHỮNG ĐƯỜNG ĐI VÔ HÌNH',note:'Không chạm vào nhau, vẫn chuyển động cùng nhau.',side:'left'},
 {id:'tidal',name:'Thủy triều',en:'Tidal',title:['Lắng nghe','một làn sóng.'],text:'Kim loại trở nên mềm mại. Những đường nhấp nhô giữ lại khoảnh khắc mặt nước vừa chuyển mình.',label:'NHỊP ĐIỆU CỦA VẬT CHẤT',note:'Hãy chậm lại ở nơi mọi thứ đang trôi.',side:'right'},
 {id:'bloom',name:'Nở rộ',en:'Bloom',title:['Một chuyển động.','Ngàn cách nở.'],text:'Từ những mảnh ghép giống nhau, một hình thái hữu cơ xuất hiện. Trật tự cũng có thể mang dáng hình của sự sống.',label:'KHI HÌNH HỌC THỞ',note:'Sự sống không bao giờ chỉ có một hình dạng.',side:'left'},
 {id:'fracture',name:'Phân rã',en:'Fracture',title:['Buông khỏi','hình hài.'],text:'Những mảnh kim loại tách ra, mở một khoảng trời ở giữa. Hãy để mọi thứ được tự do trong chốc lát.',label:'VẺ ĐẸP CỦA SỰ KHÔNG TOÀN VẸN',note:'Chưa thành hình không có nghĩa là không tồn tại.',side:'center'},
 {id:'converge',name:'Hội tụ',en:'Convergence',title:['Tìm nhau.','Thành một.'],text:'Từng mảnh rời rạc trở về trong một trật tự mới. Không phải hình hài ban đầu, nhưng vẫn là chính nó.',label:'MỘT TRẬT TỰ MỚI',note:'Tất cả những gì đã đi qua đều để lại dấu vết.',side:'right'},
 {id:'echo',name:'Dư âm',en:'Afterglow',title:['Mang theo','một khoảng lặng.'],text:'Hành trình khép lại. Góc nhìn của bạn có thể đã khác. Ở lại thêm một chút, hoặc bắt đầu thêm một lần.',label:'CẢM ƠN BẠN ĐÃ DỪNG LẠI',note:'LIMEN / Một triển lãm thử nghiệm phi thương mại.',side:'final'},
];
